# Understanding Faiss

In [1]:
# #Install Packages
!pip install faiss-cpu
!pip install sentence-transformers


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: C:\Users\vishn\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


  Using cached sentence_transformers-3.3.1-py3-none-any.whl.metadata (10 kB)
  Using cached scikit_learn-1.6.0-cp311-cp311-win_amd64.whl.metadata (15 kB)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Using cached sentence_transformers-3.3.1-py3-none-any.whl (268 kB)
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.1 MB 2.1 MB/s eta 0:00:06
   --- ------------------------------------ 1.0/11.1 MB 2.2 MB/s eta 0:00:05
   ----- ---------------------------------- 1.6/11.1 MB 2.3 MB/s eta 0:00:05
   ------- -------------------------------- 2.1/11.1 MB 2.3 MB/s eta 0:00:04
   -------- ------------------------------- 2.4/11.1 MB 2.2 MB/s eta 0:00:05
   ----------- ---------------------------- 3.1/11.1 MB 2.3 MB/s eta 0:00:04
   ------------- -------------------------- 3.7/11.1 MB 2.3 MB/s eta 0:00:04
   -------------- -------------


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: C:\Users\vishn\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
# import pandas 
import pandas as pd 

In [3]:
df = pd.read_csv("FAISS_text.csv")

In [4]:
df

text category
0      Meditation and yoga can improve mental health   Health
1  Fruits, whole grains and vegetables helps cont...   Health
2  These are the latest fashion trends for this week  Fashion
3  Vibrant color jeans for male are becoming a trend  Fashion
4                 The concert starts at 7 PM tonight    Event
5  Navaratri dandiya program at Expo center in Mu...    Event
6  Exciting vacation destinations for your next trip   Travel
7  Maldives and Srilanka are gaining popularity i...   Travel

In [5]:
from sentence_transformers import SentenceTransformer

In [6]:
# Hugging face encoder 
encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df.text)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

C:\Users\vishn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\huggingface_hub\file_download.py:159: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\vishn\.cache\huggingface\hub\models--sentence-transformers--all-mpnet-base-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

C:\Users\vishn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [7]:
vectors

array([[-0.00247395,  0.03626723, -0.05290459, ..., -0.09152358,
        -0.03969997, -0.04330491],
       [-0.03357265,  0.00980516, -0.0325013 , ..., -0.05165467,
         0.02245887, -0.03156184],
       [-0.0186532 , -0.04051321, -0.01235388, ...,  0.00610587,
        -0.07179647,  0.02773852],
       ...,
       [-0.00066458,  0.04252128, -0.05645507, ...,  0.01315469,
        -0.03183567, -0.04357662],
       [-0.03317154,  0.03252459, -0.0248484 , ...,  0.01174422,
         0.05747123,  0.00571021],
       [-0.00166393,  0.00413826, -0.04597082, ...,  0.02008527,
         0.05656241, -0.00161597]], dtype=float32)

In [8]:
vectors.shape

(8, 768)

In [9]:
vectors[0]

array([-2.47394782e-03,  3.62672284e-02, -5.29045910e-02, -2.17348523e-02,
        1.41723584e-02, -1.01601321e-03,  2.23637447e-02,  3.65196541e-02,
        3.80901471e-02,  5.22008305e-03, -3.00865285e-02,  2.05448293e-03,
        1.08502982e-02, -8.49087983e-02, -5.57269342e-03, -6.06597811e-02,
        2.32011196e-03, -1.51408920e-02,  1.20670842e-02,  1.98905040e-02,
       -1.27936425e-02, -2.72811316e-02, -3.31878588e-02,  3.40651162e-03,
        8.41168687e-03, -1.94854923e-02,  4.88132313e-02,  2.24118829e-02,
        4.53466959e-02, -5.90892062e-02, -9.13182274e-02, -1.22328498e-03,
       -4.05045897e-02,  8.67183879e-03,  1.26565260e-06, -1.92451347e-02,
       -3.20659317e-02, -4.08172607e-02,  8.79177302e-02, -1.52632073e-02,
        1.09908823e-02, -4.47976999e-02, -4.74821264e-03,  3.52632515e-02,
        1.31070344e-02,  1.09943990e-02, -3.45763541e-03,  9.12348777e-02,
        5.68809882e-02,  4.82893772e-02, -4.51438362e-03,  3.58451344e-02,
       -2.44210456e-02, -

In [11]:
dim = vectors.shape[1]

In [12]:
dim

768

In [13]:
import faiss
index = faiss.IndexFlatL2(dim)

In [14]:
index


<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x000002882942C930> >

In [15]:
index.add(vectors)

In [16]:
search_query = "An apple a day keeps doctor away"

In [17]:
vec = encoder.encode(search_query)

In [18]:
vec.shape

(768,)

In [19]:
import numpy as np 
svec = np.array(vec).reshape(1,-1)

In [20]:
svec.shape

(1, 768)

In [21]:
index.search(svec, k=2)

(array([[1.3908098, 1.7193402]], dtype=float32), array([[1, 0]], dtype=int64))

In [22]:
dis, I = index.search(svec, k=2)

In [23]:
dis

array([[1.3908098, 1.7193402]], dtype=float32)

In [24]:
I

array([[1, 0]], dtype=int64)

In [25]:
df.loc[I[0]]

text category
1  Fruits, whole grains and vegetables helps cont...   Health
0      Meditation and yoga can improve mental health   Health